### ISSUE TITLE
Rename "project" attribute

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#3]
### Motivation

Due to the historical meaning of "project" in Kontent.ai, I would recommend changing `--project=` to `--accelerator=` 

Although the accelerators are projects in their original form, this is internal and external customers never experience the accelerators as projects; only as targettable entities that they can import via codenames.

**Comment by Enngage** [comment]
@mberry1989 I've renamed it to `model` instead of `accelerator`, is that ok? My reasoning for doing so is that I also want to use `kontent-ai-accelerator` instead of `kda` to make it really clear what tools is being used. I'm using this naming in the migration-toolkit as well. 

And I wanted to avoid using the word `accelerator` twice in the command, therefore `model` :) Hope that it's ok this way. Let me know if you think otherwise.

**Comment by Enngage** [comment]
I can also use command such as `content-model-accelerator` (which is part of the npm package name).
