### ISSUE TITLE
Tool does not proceed after "Fetch"

### ISSUE THREAD

**Issue by mberry1989** [Kontent-ai-consulting/kontent-ai-model-accelerator#7]
### Brief bug description

After confirming the prompt to import the models, the terminal exits the command.

### Repro steps

1. Run:
`kontent-ai-accelerator --action=remoteImport --environmentId=<removedForIssue> --apiKey=<removedForIssue> --model=advanced_person`
2. Type "y" to confirm the prompt
3. See "Fetch" message and the command stops.

### Expected behavior

1. Import informs the user of what is being imported and completes successfully.

### Minor edit:
The "prompt" has a lowercase "y" and an uppercase "N" for options.

**Comment by Enngage** [comment]
There was an issue displaying error message which I've fixed now. The main reason it stops after fetch in this case is because such model doesn't exist:

```bash
[Error]: Could not find accelerator model with codename 'advanced_person'
``` 

Remember that it is currently connected to the `dev` environment within our Learn project. The item must be published there to be available via CLI. You can also run

```bash
kontent-ai-accelerator --action=list
```

to see a list of available models. 

As for `y/N` - this seems to be the default semantics that is used when using the yes/no prompt type :) 

![gh](https://github.com/Kontent-ai-consulting/kontent-ai-model-accelerator/assets/7137351/1bbb7022-aa19-4e74-9fce-c0bac4ea7c48)
